server:
  port: 8080
jwt:
  header: Authorization
  expiration: '604800'
  secret: dejavu
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: '576120233850127'
            scope: email,public_profile
            client-secret: 1d382f3be570af6340fe53dde6cc3ba1
          github:
            client-secret: 58eceb619b5f9e7826116eececa9fdfdde3bb028
            client-id: d7bf23b2dc5a4f9ebef5
            scope: user:email,read:user
          google:
            client-id: 231038597470-jlvplv4aa79dskqnlldunorp7gpqmo0u.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            user-info-uri: https://graph.facebook.com/v10.0/me?fields=email,first_name,last_name,name
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate #Eğer Create olursa tabloyu baştan yaratır
  mail:
    username: inc.bringtome@gmail.com
    port: '465'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    protocol: smtps
    password: bringtome61
  servlet:
    multipart:
      enabled: 'true'
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2MB
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bringtome"
    username: postgres
    password: 180200
mail:
  debug: 'false'
hostname: localhost:3000
logging:
  level:
    com:
      bringtome:
        ecommerce:
          controller: debug
recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s
  secret: 6Ldt-OYiAAAAAP6NAMf9f_hFT0GLqMQAPc5yHZA8