server:
  port: 8080
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bcclip"
    username: postgres
    password: 180200
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate #Eğer Create olursa tabloyu baştan yaratır